# Generated by Django 5.2.8 on 2025-11-19 14:36

from django.db import migrations

def seed_categories(apps, schema_editor):
    Category = apps.get_model('transactions', 'Category')
    categories = [
        "Renda",
        "Alimentação",
        "Transporte",
        "Casa",
        "Aluguel",
        "Saúde",
        "Lazer",
        "Compras",
        "Educação",
        "Beleza",
        "Investimento",

    ]
    for name in categories:
        Category.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transacao_category'),
    ]

    operations = [
        migrations.RunPython(seed_categories),
    ]
