# Generated by Django 5.2.8 on 2025-11-11 02:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('whatsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('date_transaction', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('IN', 'Income'), ('OUT', 'Expense'), ('TRANS', 'Transference')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.category')),
                ('message', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='whatsapp.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_transaction', '-id'],
                'indexes': [models.Index(fields=['user', 'date_transaction'], name='transaction_user_id_3acdd6_idx'), models.Index(fields=['type'], name='transaction_type_f88d7c_idx')],
            },
        ),
    ]
